local QBCore = exports['qb-core']:GetCoreObject()
isLoggedIn = false
PlayerGang = {}
PlayerJob = {}



TriggerEvent('QBCore:GetObject', function(obj) QBCore = obj end)


RegisterNetEvent('QBCore:Client:OnPlayerLoaded')
AddEventHandler('QBCore:Client:OnPlayerLoaded', function()
    isLoggedIn = true
    PlayerGang = QBCore.Functions.GetPlayerData().gang
    QBCore.Functions.GetPlayerData(function(PlayerData)
        PlayerJob = PlayerData.job
    end)
   
end)


RegisterNetEvent('QBCore:Client:OnPlayerUnload')
AddEventHandler('QBCore:Client:OnPlayerUnload', function()
    isLoggedIn = false
end)

RegisterNetEvent('QBCore:Client:OnJobUpdate', function(JobInfo)
    PlayerJob = JobInfo
end)



RegisterNetEvent('QBCore:Client:OnGangUpdate')
AddEventHandler('QBCore:Client:OnGangUpdate', function(GangInfo)
    PlayerGang = GangInfo
    isLoggedIn = true
end)


Citizen.CreateThread(function()
    while true do
     Wait(0)
    if PlayerJob.name == "police" then
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
        SetRelationshipBetweenGroups(2, `SECURITY_GUARD`, `PLAYER`)
    elseif PlayerJob.name == "ambulance" then
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_BALLAS`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_FAMILY`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_SALVA`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_LOST`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_1`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_2`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_9`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_10`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `SECURITY_GUARD`, `PLAYER`)
    elseif PlayerJob.name == "fire" then
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_BALLAS`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_FAMILY`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_SALVA`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_LOST`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_1`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_2`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_9`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `GANG_10`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
        SetRelationshipBetweenGroups(0, `SECURITY_GUARD`, `PLAYER`)
    elseif PlayerJob.name == "mosley" then
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
        SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
        SetRelationshipBetweenGroups(2, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "ballas" then    
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(0, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "none" then
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `FIREMAN`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `MEDIC`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `COP`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `SECURITY_GUARD`, `PLAYER`)
    SetRelationshipBetweenGroups(1, `AMBIENT_GANG_BALLAS`, `PLAYER`)
elseif PlayerGang.name == "families" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(0, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "marabunta" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(0, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "salva" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(0, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "lostmc" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(0, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "satanpriors" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "trickster" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "cartel" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "triads" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)
elseif PlayerGang.name == "vagos" then
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_BALLAS`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_FAMILY`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_SALVA`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `AMBIENT_GANG_LOST`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_1`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_2`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_9`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `GANG_10`, `PLAYER`)
    SetRelationshipBetweenGroups(0, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
    SetRelationshipBetweenGroups(3, `SECURITY_GUARD`, `PLAYER`)

else
    Wait(1000)
end
end
end)




-- Respect entre pnj de gang ballas

SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_BALLAS`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_BALLAS`)


--  respect entre pnj hillbilly
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_HILLBILLY`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_HILLBILLY`)

-- respect entre pnj vagos
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_MEXICAN`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_MEXICAN`)

-- respect pnj entre familly
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_FAMILY`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_FAMILY`)
-- Marabunte
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_MARABUNTE`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_MARABUNTE`)
--salva
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_SALVA`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_SALVA`)
--lost
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `GANG_1`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `GANG_2`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `GANG_9`, `AMBIENT_GANG_LOST`)
SetRelationshipBetweenGroups(4, `GANG_10`, `AMBIENT_GANG_LOST`)
--Gang1
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `GANG_1`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `GANG_1`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `GANG_1`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `GANG_1`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `GANG_1`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `GANG_1`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `GANG_1`)
SetRelationshipBetweenGroups(4, `GANG_2`, `GANG_1`)
SetRelationshipBetweenGroups(4, `GANG_9`, `GANG_1`)
SetRelationshipBetweenGroups(4, `GANG_10`, `GANG_1`)
--Gang2
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `GANG_2`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `GANG_2`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `GANG_2`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `GANG_2`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `GANG_2`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `GANG_2`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `GANG_2`)
SetRelationshipBetweenGroups(4, `GANG_1`, `GANG_2`)
SetRelationshipBetweenGroups(4, `GANG_9`, `GANG_2`)
SetRelationshipBetweenGroups(4, `GANG_10`, `GANG_2`)
--gang9
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `GANG_9`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `GANG_9`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `GANG_9`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `GANG_9`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `GANG_9`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `GANG_9`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `GANG_9`)
SetRelationshipBetweenGroups(4, `GANG_1`, `GANG_9`)
SetRelationshipBetweenGroups(4, `GANG_2`, `GANG_9`)
SetRelationshipBetweenGroups(4, `GANG_10`, `GANG_9`)
--Gang 10
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_HILLBILLY`, `GANG_10`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_BALLAS`, `GANG_10`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MEXICAN`, `GANG_10`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_FAMILY`, `GANG_10`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_MARABUNTE`, `GANG_10`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_SALVA`, `GANG_10`)
SetRelationshipBetweenGroups(4, `AMBIENT_GANG_LOST`, `GANG_10`)
SetRelationshipBetweenGroups(4, `GANG_1`, `GANG_10`)
SetRelationshipBetweenGroups(4, `GANG_2`, `GANG_10`)
SetRelationshipBetweenGroups(4, `GANG_9`, `GANG_10`)




